### ISSUE TITLE
Awesome! What OS versions does it work on?

### ISSUE THREAD

**Issue by E3V3A** [mykle1/MMM-FMI#1]
What a great idea! 
Does it give GPS coordinates back? 
What iOS versions does it support?

**Comment by mykle1** [comment]
I wish it was my idea. CBD got rid of his iPhone and offered the unfinished module to me. I'll post a picture of the return so you can see the data. It supports any iOS version that includes the "Find My iPhone" feature. In fact, any Mac device. It finds my iPad and my iMac, too. 

I'm thinking about attempting a Hello-Lucy voice command that launches the module. Right now, you have to click to launch.
