### ISSUE TITLE
Can you use a voice command to search for phone?

### ISSUE THREAD

**Issue by grallr2** [mykle1/MMM-FMI#2]
Hi Mykle,

I love your hello lucy module and i'm looking to use the MMM-FMI module. I have it working to the point that it can ping a sound to my iPhone. Is it possible to integrate a voice command to this rather than using a mouse to click the textbox? Also says undefined under the icon.

Regards
Rob

**Comment by mykle1** [comment]
I will look into this when I have some free time. I'm swamped at the moment with some newer projects. I do appreciate your kind words regarding Lucy. Lucy is undergoing a total re-write at the moment.

Sorry for the delay. Peace!

Mykle

**Comment by grallr2** [comment]
Hi Mykle,

Thanks very much for getting back to me.

Best regards,
Rob

**Comment by mykle1** [comment]
Rob, until I can get to this I wanted to tell you that you can fork the repo and make the modifications yourself. You can enter a pull request if you want your changes to be written to the module and repo. That is, if you want to.

**Comment by mykle1** [comment]
I closed this issue because it is more of a feature request than an issue with the module
