### ISSUE TITLE
How to work when your Apple ID has enabled two-factor authentication

### ISSUE THREAD

**Issue by xuepgao** [mykle1/MMM-FMI#3]
@mykle1 

Thank you for providing us with this fantastic module!

As you know, Apple has enabled two-factor authentication mechanism for user's Apple ID since last year.  
I installed and configured the MMM-FMI module. After I clicked the button on the module alert-box windows, my iPhone received a double confirm windows. It tell me where my apple id now is logining from...
When I approved this message, the MMM-FMI module can work fine. The question is that this modules is for finding my iPhone, how can I approve a two-factor authentication login on my iPhone?

Apple tell me that  two-factor authentication mechanism once be enabled, you can never turn it off! I try to use **app password** of my iCloud ID for MMM-FMI module in in config.js. When I run MM2 again, a login error displays in console:

**`_<error> Login Error (/home/pi/MagicMirror/js/app.js:35 process.<anonymous>)_`**

The find-my-phone functionof the MMM-FMI module does not support app password?

Could you give me some suggestion? Thanks in advance.

**Comment by mykle1** [comment]
You absolutely CAN turn off two factor authentication on your iphone. The directions for doing that can be found using a simple search. The module is not designed to work with two-factor authentication and I don't have any plans to rewrite the module. Feel free to fork the repo and make the changes yourself. I am open to any pull requests

**Comment by xuepgao** [comment]
@mykle1 

Thanks for your reply.

I don't think you are using iPhone now. Apple forbid users to disable two-factor authentication now. I'm sure this point after I called Apple help desk and searched related documents.
![image](https://user-images.githubusercontent.com/48181152/56177861-c0c0c180-6032-11e9-9a8a-1e964db7890b.png)

**Comment by mykle1** [comment]
I did not  know this. I have an older iPhone 6 with iOS 11.2.6. At that time you could turn off the authentication. I'm sorry that you cannot. I don't think it can be fixed at the npm package being used in the module does not account for that.
